AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CreateCaseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/CreateCase.handler
      Runtime: nodejs8.10