AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: POC of a serverless event sourcing system. OK to delete after May 2018
Globals:
  Api:
    Cors: 
      AllowOrigin: "'*'"
      AllowMethods: "HEAD,OPTIONS,GET,POST,PUT,PATCH"
Resources:
  CreateRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/requests/events/CreateController.submitEvent
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          REQUEST_EVENTS_TABLE_NAME: !Ref RequestEventsTable
      Events:
        CreateRequest:
          Type: Api
          Properties:
            Path: /requests/{requestId}/events/create
            Method: post
  ReviewRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/requests/events/ReviewController.submitEvent
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          REQUEST_EVENTS_TABLE_NAME: !Ref RequestEventsTable
      Events:
        ReviewRequest:
          Type: Api
          Properties:
            Path: /requests/{requestId}/events/review
            Method: post
  ListRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/requests/ListRequests.handler
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          REQUEST_SNAPSHOTS_TABLE_NAME: !Ref RequestSnapshotTable
      Events:
        ReviewRequest:
          Type: Api
          Properties:
            Path: /requests
            Method: get
  RequestSnapshotUpdater:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/requests/SnapshotUpdateController.handler
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          REQUEST_EVENTS_TABLE_NAME: !Ref RequestEventsTable
          REQUEST_SNAPSHOTS_TABLE_NAME: !Ref RequestSnapshotTable
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt RequestEventsTable.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 1
  RequestEventsTable:
    Type: "AWS::DynamoDB::Table"
    Properties: 
      AttributeDefinitions: 
        - AttributeName: requestId
          AttributeType: S
        - AttributeName: eventTimestamp
          AttributeType: S
      KeySchema: 
        - AttributeName: requestId
          KeyType: HASH
        - AttributeName: eventTimestamp
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  RequestSnapshotTable:
    Type: "AWS::DynamoDB::Table"
    Properties: 
      AttributeDefinitions: 
        - AttributeName: requestId
          AttributeType: S
      KeySchema: 
        - AttributeName: requestId
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
Outputs:
  RestApiEndpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"