AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: POC of a serverless event sourcing system. OK to delete after May 2018
Resources:
  CreateRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/requests/events/CreateEvent.handler
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          REQUEST_EVENTS_TABLE_NAME: !Ref RequestEventsTable
      Events:
        CreateRequest:
          Type: Api
          Properties:
            Path: /requests/{requestId}/events/create
            Method: post
  RequestEventsTable:
    Type: "AWS::DynamoDB::Table"
    Properties: 
      AttributeDefinitions: 
        - AttributeName: requestId
          AttributeType: S
        - AttributeName: eventTimestamp
          AttributeType: S
      KeySchema: 
        - AttributeName: requestId
          KeyType: HASH
        - AttributeName: eventTimestamp
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2